name: wenv test suite

on:
    push: {}
    schedule:
        - cron: '30 9 7 * *'

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo sh -c "curl https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor > /etc/apt/trusted.gpg.d/winehq.gpg"
          sudo sh -c "apt-add-repository \"https://dl.winehq.org/wine-builds/ubuntu\""
          sudo apt update
          sudo apt upgrade
          sudo apt --fix-broken install
          sudo apt remove nginx nginx-common
          sudo apt --fix-broken install
          echo "G"
          sudo apt install -y --install-recommends update-motd:i386 libselinux1:i386 libpam-modules:i386 login:i386 libmount1:i386 libpam0g:i386 libgssapi-krb5-2:i386 libglib2.0-0:i386 fontconfig-config:i386 libglib2.0-0:i386
          echo "F"
          sudo apt install -y --install-recommends libpcre2-8-0:i386
          echo "E"
          sudo apt install -y --install-recommends libselinux1:i386
          echo "D"
          sudo apt install -y --install-recommends libmount1:i386
          echo "C"
          sudo apt install -y --install-recommends libglib2.0-0:i386
          echo "B"
          sudo apt install -y --install-recommends wine-staging-i386
          echo "A"
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update Python infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
      - name: Install wenv package
        run: |
          make install
      - name: Pre-check
        run: |
          wine --version
          wine64 --version
          python --version
          pytest --version
          uname -a
          lsb_release -a
          wenv --version
      - name: Build docs
        run: |
          make docs
      - name: Run tests
        run: |
          make test
