name: wenv test suite

on:
    push: {}
    schedule:
        - cron: '30 9 7 * *'

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo sh -c "curl https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor > /etc/apt/trusted.gpg.d/winehq.gpg"
          sudo "apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main'"
          sudo apt-get -qq update
          sudo apt-get install -y winehq-staging
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update Python infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
      - name: Install wenv package
        run: |
          make install
      - name: Pre-check
        run: |
          wine --version
          wine64 --version
          python --version
          pytest --version
          uname -a
          lsb_release -a
          wenv --version
      - name: Build docs
        run: |
          make docs
      - name: Run tests
        run: |
          make test
